# Generated by cstruct-stubgen
from typing import BinaryIO, overload

import dissect.cstruct as __cs__
from typing_extensions import TypeAlias

class _c_rockridge(__cs__.cstruct):
    class SU_SP_s(__cs__.Structure):
        signature: __cs__.CharArray
        length: _c_rockridge.uint8
        version: _c_rockridge.uint8
        check_bytes: __cs__.CharArray
        len_skp: _c_rockridge.uint8
        @overload
        def __init__(
            self,
            signature: __cs__.CharArray | None = ...,
            length: _c_rockridge.uint8 | None = ...,
            version: _c_rockridge.uint8 | None = ...,
            check_bytes: __cs__.CharArray | None = ...,
            len_skp: _c_rockridge.uint8 | None = ...,
        ): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

    class SU_CE_s(__cs__.Structure):
        signature: __cs__.CharArray
        length: _c_rockridge.uint8
        version: _c_rockridge.uint8
        extent: _c_rockridge.uint32
        extent_be: __cs__.CharArray
        offset: _c_rockridge.uint32
        offset_be: __cs__.CharArray
        size: _c_rockridge.uint32
        size_be: __cs__.CharArray
        @overload
        def __init__(
            self,
            signature: __cs__.CharArray | None = ...,
            length: _c_rockridge.uint8 | None = ...,
            version: _c_rockridge.uint8 | None = ...,
            extent: _c_rockridge.uint32 | None = ...,
            extent_be: __cs__.CharArray | None = ...,
            offset: _c_rockridge.uint32 | None = ...,
            offset_be: __cs__.CharArray | None = ...,
            size: _c_rockridge.uint32 | None = ...,
            size_be: __cs__.CharArray | None = ...,
        ): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

    class SU_ER_s(__cs__.Structure):
        signature: __cs__.CharArray
        length: _c_rockridge.uint8
        version: _c_rockridge.uint8
        len_id: _c_rockridge.uint8
        len_des: _c_rockridge.uint8
        len_src: _c_rockridge.uint8
        ext_ver: _c_rockridge.uint8
        identifier: __cs__.CharArray
        description: __cs__.CharArray
        source: __cs__.CharArray
        @overload
        def __init__(
            self,
            signature: __cs__.CharArray | None = ...,
            length: _c_rockridge.uint8 | None = ...,
            version: _c_rockridge.uint8 | None = ...,
            len_id: _c_rockridge.uint8 | None = ...,
            len_des: _c_rockridge.uint8 | None = ...,
            len_src: _c_rockridge.uint8 | None = ...,
            ext_ver: _c_rockridge.uint8 | None = ...,
            identifier: __cs__.CharArray | None = ...,
            description: __cs__.CharArray | None = ...,
            source: __cs__.CharArray | None = ...,
        ): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

    class RR_PX_s(__cs__.Structure):
        signature: __cs__.CharArray
        length: _c_rockridge.uint8
        version: _c_rockridge.uint8
        mode: _c_rockridge.uint32
        mode_be: __cs__.CharArray
        links: _c_rockridge.uint32
        links_be: __cs__.CharArray
        uid: _c_rockridge.uint32
        uid_be: __cs__.CharArray
        gid: _c_rockridge.uint32
        gid_be: __cs__.CharArray
        @overload
        def __init__(
            self,
            signature: __cs__.CharArray | None = ...,
            length: _c_rockridge.uint8 | None = ...,
            version: _c_rockridge.uint8 | None = ...,
            mode: _c_rockridge.uint32 | None = ...,
            mode_be: __cs__.CharArray | None = ...,
            links: _c_rockridge.uint32 | None = ...,
            links_be: __cs__.CharArray | None = ...,
            uid: _c_rockridge.uint32 | None = ...,
            uid_be: __cs__.CharArray | None = ...,
            gid: _c_rockridge.uint32 | None = ...,
            gid_be: __cs__.CharArray | None = ...,
        ): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

    class RR_NM_s(__cs__.Structure):
        signature: __cs__.CharArray
        len: _c_rockridge.uint8
        version: _c_rockridge.uint8
        _continue: _c_rockridge.uint8
        current: _c_rockridge.uint8
        parent: _c_rockridge.uint8
        reserved_one: _c_rockridge.uint8
        reserved_two: _c_rockridge.uint8
        reserved_three: _c_rockridge.uint8
        name: __cs__.CharArray
        @overload
        def __init__(
            self,
            signature: __cs__.CharArray | None = ...,
            len: _c_rockridge.uint8 | None = ...,
            version: _c_rockridge.uint8 | None = ...,
            _continue: _c_rockridge.uint8 | None = ...,
            current: _c_rockridge.uint8 | None = ...,
            parent: _c_rockridge.uint8 | None = ...,
            reserved_one: _c_rockridge.uint8 | None = ...,
            reserved_two: _c_rockridge.uint8 | None = ...,
            reserved_three: _c_rockridge.uint8 | None = ...,
            name: __cs__.CharArray | None = ...,
        ): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

    class SL_component_flags(__cs__.Structure):
        _continue: _c_rockridge.uint8
        current: _c_rockridge.uint8
        parent: _c_rockridge.uint8
        root: _c_rockridge.uint8
        reserved_one: _c_rockridge.uint8
        reserved_two: _c_rockridge.uint8
        reserved: _c_rockridge.uint8
        @overload
        def __init__(
            self,
            _continue: _c_rockridge.uint8 | None = ...,
            current: _c_rockridge.uint8 | None = ...,
            parent: _c_rockridge.uint8 | None = ...,
            root: _c_rockridge.uint8 | None = ...,
            reserved_one: _c_rockridge.uint8 | None = ...,
            reserved_two: _c_rockridge.uint8 | None = ...,
            reserved: _c_rockridge.uint8 | None = ...,
        ): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

    class SL_component(__cs__.Structure):
        flags: _c_rockridge.SL_component_flags
        len: _c_rockridge.uint8
        content: __cs__.CharArray
        @overload
        def __init__(
            self,
            flags: _c_rockridge.SL_component_flags | None = ...,
            len: _c_rockridge.uint8 | None = ...,
            content: __cs__.CharArray | None = ...,
        ): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

    class RR_SL_s(__cs__.Structure):
        signature: __cs__.CharArray
        len: _c_rockridge.uint8
        version: _c_rockridge.uint8
        continue_flag: _c_rockridge.uint8
        reserved_flag_bits: _c_rockridge.uint8
        components: __cs__.CharArray
        @overload
        def __init__(
            self,
            signature: __cs__.CharArray | None = ...,
            len: _c_rockridge.uint8 | None = ...,
            version: _c_rockridge.uint8 | None = ...,
            continue_flag: _c_rockridge.uint8 | None = ...,
            reserved_flag_bits: _c_rockridge.uint8 | None = ...,
            components: __cs__.CharArray | None = ...,
        ): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

    class RR_TF_s(__cs__.Structure):
        signature: __cs__.CharArray
        len: _c_rockridge.uint8
        version: _c_rockridge.uint8
        CREATION: _c_rockridge.uint8
        MODIFY: _c_rockridge.uint8
        ACCESS: _c_rockridge.uint8
        ATTRIBUTES: _c_rockridge.uint8
        BACKUP: _c_rockridge.uint8
        EXPIRATION: _c_rockridge.uint8
        EFFECTIVE: _c_rockridge.uint8
        LONG_FORM: _c_rockridge.uint8
        @overload
        def __init__(
            self,
            signature: __cs__.CharArray | None = ...,
            len: _c_rockridge.uint8 | None = ...,
            version: _c_rockridge.uint8 | None = ...,
            CREATION: _c_rockridge.uint8 | None = ...,
            MODIFY: _c_rockridge.uint8 | None = ...,
            ACCESS: _c_rockridge.uint8 | None = ...,
            ATTRIBUTES: _c_rockridge.uint8 | None = ...,
            BACKUP: _c_rockridge.uint8 | None = ...,
            EXPIRATION: _c_rockridge.uint8 | None = ...,
            EFFECTIVE: _c_rockridge.uint8 | None = ...,
            LONG_FORM: _c_rockridge.uint8 | None = ...,
        ): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

    class RR_CL_s(__cs__.Structure):
        signature: __cs__.CharArray
        len: _c_rockridge.uint8
        version: _c_rockridge.uint8
        location: _c_rockridge.uint32
        location_be: __cs__.CharArray
        @overload
        def __init__(
            self,
            signature: __cs__.CharArray | None = ...,
            len: _c_rockridge.uint8 | None = ...,
            version: _c_rockridge.uint8 | None = ...,
            location: _c_rockridge.uint32 | None = ...,
            location_be: __cs__.CharArray | None = ...,
        ): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

    class RR_PL_s(__cs__.Structure):
        signature: __cs__.CharArray
        len: _c_rockridge.uint8
        version: _c_rockridge.uint8
        location: _c_rockridge.uint32
        location_be: __cs__.CharArray
        @overload
        def __init__(
            self,
            signature: __cs__.CharArray | None = ...,
            len: _c_rockridge.uint8 | None = ...,
            version: _c_rockridge.uint8 | None = ...,
            location: _c_rockridge.uint32 | None = ...,
            location_be: __cs__.CharArray | None = ...,
        ): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

    class system_use_entry(__cs__.Structure):
        signature: __cs__.CharArray
        len: _c_rockridge.uint8
        version: _c_rockridge.uint8
        data: __cs__.CharArray
        @overload
        def __init__(
            self,
            signature: __cs__.CharArray | None = ...,
            len: _c_rockridge.uint8 | None = ...,
            version: _c_rockridge.uint8 | None = ...,
            data: __cs__.CharArray | None = ...,
        ): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

# Technically `c_rockridge` is an instance of `_c_rockridge`, but then we can't use it in type hints
c_rockridge: TypeAlias = _c_rockridge
