# Generated by cstruct-stubgen
from typing import BinaryIO, Literal, overload

import dissect.cstruct as __cs__
from typing_extensions import TypeAlias

class _c_udf(__cs__.cstruct):
    NSR_DESCRIPTOR_MAGIC: Literal[b"NSR02"] = ...
    TEA_DESCRIPTOR_MAGIC: Literal[b"TEA01"] = ...
    BOOT_DESCRIPTOR_MAGIC: Literal[b"BOOT2"] = ...
    BEA_DESCRIPTOR_MAGIC: Literal[b"BEA01"] = ...
    GP_PARTITION_MAP_TYPE_UNDEF: Literal[0] = ...
    GP_PARTITION_MAP_TYPE_1: Literal[1] = ...
    GP_PARTITION_MAP_TYPE_2: Literal[2] = ...
    class udf_charspec(__cs__.Structure):
        charset_type: _c_udf.uint8
        charset_info: __cs__.CharArray
        @overload
        def __init__(self, charset_type: _c_udf.uint8 | None = ..., charset_info: __cs__.CharArray | None = ...): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

    class udf_entity_id(__cs__.Structure):
        flags: _c_udf.uint8
        identifier: __cs__.CharArray
        identifier_suffix: __cs__.CharArray
        @overload
        def __init__(
            self,
            flags: _c_udf.uint8 | None = ...,
            identifier: __cs__.CharArray | None = ...,
            identifier_suffix: __cs__.CharArray | None = ...,
        ): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

    class udf_timestamp(__cs__.Structure):
        type: _c_udf.int16
        timezone: _c_udf.int16
        year: _c_udf.int16
        month: _c_udf.uint8
        day: _c_udf.uint8
        hour: _c_udf.uint8
        minute: _c_udf.uint8
        second: _c_udf.uint8
        centiseconds: _c_udf.uint8
        hundreds_of_microseconds: _c_udf.uint8
        microseconds: _c_udf.uint8
        @overload
        def __init__(
            self,
            type: _c_udf.int16 | None = ...,
            timezone: _c_udf.int16 | None = ...,
            year: _c_udf.int16 | None = ...,
            month: _c_udf.uint8 | None = ...,
            day: _c_udf.uint8 | None = ...,
            hour: _c_udf.uint8 | None = ...,
            minute: _c_udf.uint8 | None = ...,
            second: _c_udf.uint8 | None = ...,
            centiseconds: _c_udf.uint8 | None = ...,
            hundreds_of_microseconds: _c_udf.uint8 | None = ...,
            microseconds: _c_udf.uint8 | None = ...,
        ): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

    class udf_extent_ad(__cs__.Structure):
        extent_length: _c_udf.uint32
        extent_location: _c_udf.uint32
        @overload
        def __init__(self, extent_length: _c_udf.uint32 | None = ..., extent_location: _c_udf.uint32 | None = ...): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

    class udf_tag_identifier(__cs__.Enum):
        PVD = ...
        AVDP = ...
        VDP = ...
        IUVD = ...
        PD = ...
        LVD = ...
        USD = ...
        TD = ...
        LVID = ...
        FSD = ...
        FID = ...
        AED = ...
        IE = ...
        TE = ...
        FE = ...
        EAHD = ...
        USE = ...
        SBD = ...
        PIE = ...
        EFE = ...

    class udf_tag(__cs__.Structure):
        identifier: _c_udf.udf_tag_identifier
        descriptor_version: _c_udf.uint16
        tag_checksum: _c_udf.uint8
        reserved: _c_udf.char
        tag_serial_number: _c_udf.uint16
        descriptor_crc: _c_udf.uint16
        descriptor_crc_length: _c_udf.uint16
        tag_location: _c_udf.uint32
        @overload
        def __init__(
            self,
            identifier: _c_udf.udf_tag_identifier | None = ...,
            descriptor_version: _c_udf.uint16 | None = ...,
            tag_checksum: _c_udf.uint8 | None = ...,
            reserved: _c_udf.char | None = ...,
            tag_serial_number: _c_udf.uint16 | None = ...,
            descriptor_crc: _c_udf.uint16 | None = ...,
            descriptor_crc_length: _c_udf.uint16 | None = ...,
            tag_location: _c_udf.uint32 | None = ...,
        ): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

    class udf_primary_volume_descriptor(__cs__.Structure):
        volume_descriptor_sequence_number: _c_udf.uint32
        primary_volume_descriptor_number: _c_udf.uint32
        volume_identifier: __cs__.CharArray
        volume_sequence_number: _c_udf.uint16
        maximum_volume_sequence_number: _c_udf.uint16
        interchange_level: _c_udf.uint16
        maximum_interchange_level: _c_udf.uint16
        character_set_list: _c_udf.uint32
        maximum_character_set_list: _c_udf.uint32
        volume_set_identifier: __cs__.CharArray
        descriptor_character_set: _c_udf.udf_charspec
        explanatory_character_set: _c_udf.udf_charspec
        volume_abstract: _c_udf.udf_extent_ad
        volume_copyright_notice: _c_udf.udf_extent_ad
        application_identifier: _c_udf.udf_entity_id
        recording_date_and_time: _c_udf.udf_timestamp
        implementation_identifier: _c_udf.udf_entity_id
        implementation_use: __cs__.CharArray
        predecessor_volume_descriptor_sequence_location: _c_udf.uint32
        flags: _c_udf.uint16
        reserved: __cs__.CharArray
        @overload
        def __init__(
            self,
            volume_descriptor_sequence_number: _c_udf.uint32 | None = ...,
            primary_volume_descriptor_number: _c_udf.uint32 | None = ...,
            volume_identifier: __cs__.CharArray | None = ...,
            volume_sequence_number: _c_udf.uint16 | None = ...,
            maximum_volume_sequence_number: _c_udf.uint16 | None = ...,
            interchange_level: _c_udf.uint16 | None = ...,
            maximum_interchange_level: _c_udf.uint16 | None = ...,
            character_set_list: _c_udf.uint32 | None = ...,
            maximum_character_set_list: _c_udf.uint32 | None = ...,
            volume_set_identifier: __cs__.CharArray | None = ...,
            descriptor_character_set: _c_udf.udf_charspec | None = ...,
            explanatory_character_set: _c_udf.udf_charspec | None = ...,
            volume_abstract: _c_udf.udf_extent_ad | None = ...,
            volume_copyright_notice: _c_udf.udf_extent_ad | None = ...,
            application_identifier: _c_udf.udf_entity_id | None = ...,
            recording_date_and_time: _c_udf.udf_timestamp | None = ...,
            implementation_identifier: _c_udf.udf_entity_id | None = ...,
            implementation_use: __cs__.CharArray | None = ...,
            predecessor_volume_descriptor_sequence_location: _c_udf.uint32 | None = ...,
            flags: _c_udf.uint16 | None = ...,
            reserved: __cs__.CharArray | None = ...,
        ): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

    class udf_anchor_volume_descriptor_pointer(__cs__.Structure):
        descriptor_tag: _c_udf.udf_tag
        main_volume_descriptor_sequence_extent: _c_udf.udf_extent_ad
        reserve_volume_descriptor_sequence_extent: _c_udf.udf_extent_ad
        reserved: __cs__.CharArray
        @overload
        def __init__(
            self,
            descriptor_tag: _c_udf.udf_tag | None = ...,
            main_volume_descriptor_sequence_extent: _c_udf.udf_extent_ad | None = ...,
            reserve_volume_descriptor_sequence_extent: _c_udf.udf_extent_ad | None = ...,
            reserved: __cs__.CharArray | None = ...,
        ): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

    class udf_partition_descriptor(__cs__.Structure):
        volume_descriptor_sequence_number: _c_udf.uint32
        partition_flags: _c_udf.uint16
        partition_number: _c_udf.uint16
        partition_contents: _c_udf.udf_entity_id
        partition_contents_use: __cs__.CharArray
        access_type: _c_udf.uint32
        partition_starting_location: _c_udf.uint32
        partition_length: _c_udf.uint32
        implementation_identifier: _c_udf.udf_entity_id
        implementation_use: __cs__.CharArray
        reserved: __cs__.CharArray
        @overload
        def __init__(
            self,
            volume_descriptor_sequence_number: _c_udf.uint32 | None = ...,
            partition_flags: _c_udf.uint16 | None = ...,
            partition_number: _c_udf.uint16 | None = ...,
            partition_contents: _c_udf.udf_entity_id | None = ...,
            partition_contents_use: __cs__.CharArray | None = ...,
            access_type: _c_udf.uint32 | None = ...,
            partition_starting_location: _c_udf.uint32 | None = ...,
            partition_length: _c_udf.uint32 | None = ...,
            implementation_identifier: _c_udf.udf_entity_id | None = ...,
            implementation_use: __cs__.CharArray | None = ...,
            reserved: __cs__.CharArray | None = ...,
        ): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

    class udf_logical_volume_descriptor(__cs__.Structure):
        volume_descriptor_sequence_number: _c_udf.uint32
        descriptor_character_set: _c_udf.udf_charspec
        logical_volume_identifier: __cs__.CharArray
        logical_block_size: _c_udf.uint32
        domain_identifier: _c_udf.udf_entity_id
        logical_volume_contents_use: __cs__.CharArray
        map_table_length: _c_udf.uint32
        number_of_partition_maps: _c_udf.uint32
        implementation_identifier: _c_udf.udf_entity_id
        implementation_use: __cs__.CharArray
        integrity_sequence_extent: _c_udf.udf_extent_ad
        partition_maps: __cs__.CharArray
        @overload
        def __init__(
            self,
            volume_descriptor_sequence_number: _c_udf.uint32 | None = ...,
            descriptor_character_set: _c_udf.udf_charspec | None = ...,
            logical_volume_identifier: __cs__.CharArray | None = ...,
            logical_block_size: _c_udf.uint32 | None = ...,
            domain_identifier: _c_udf.udf_entity_id | None = ...,
            logical_volume_contents_use: __cs__.CharArray | None = ...,
            map_table_length: _c_udf.uint32 | None = ...,
            number_of_partition_maps: _c_udf.uint32 | None = ...,
            implementation_identifier: _c_udf.udf_entity_id | None = ...,
            implementation_use: __cs__.CharArray | None = ...,
            integrity_sequence_extent: _c_udf.udf_extent_ad | None = ...,
            partition_maps: __cs__.CharArray | None = ...,
        ): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

    class udf_generic_partition_map(__cs__.Structure):
        partition_map_type: _c_udf.uint8
        partition_map_length: _c_udf.uint8
        partition_mapping: __cs__.CharArray
        @overload
        def __init__(
            self,
            partition_map_type: _c_udf.uint8 | None = ...,
            partition_map_length: _c_udf.uint8 | None = ...,
            partition_mapping: __cs__.CharArray | None = ...,
        ): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

    class udf_partition_map_type_1(__cs__.Structure):
        partition_map_type: _c_udf.uint8
        partition_map_length: _c_udf.uint8
        volume_sequence_number: _c_udf.uint16
        partition_number: _c_udf.uint16
        @overload
        def __init__(
            self,
            partition_map_type: _c_udf.uint8 | None = ...,
            partition_map_length: _c_udf.uint8 | None = ...,
            volume_sequence_number: _c_udf.uint16 | None = ...,
            partition_number: _c_udf.uint16 | None = ...,
        ): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

    class udf_partition_map_type_2(__cs__.Structure):
        partition_map_type: _c_udf.uint8
        partition_map_length: _c_udf.uint8
        reserved: __cs__.CharArray
        partition_type_identifier: _c_udf.udf_entity_id
        volume_sequence_number: _c_udf.uint16
        partition_number: _c_udf.uint16
        data: __cs__.CharArray
        @overload
        def __init__(
            self,
            partition_map_type: _c_udf.uint8 | None = ...,
            partition_map_length: _c_udf.uint8 | None = ...,
            reserved: __cs__.CharArray | None = ...,
            partition_type_identifier: _c_udf.udf_entity_id | None = ...,
            volume_sequence_number: _c_udf.uint16 | None = ...,
            partition_number: _c_udf.uint16 | None = ...,
            data: __cs__.CharArray | None = ...,
        ): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

    class udf_lb_addr(__cs__.Structure):
        logical_block_number: _c_udf.uint32
        partition_reference_number: _c_udf.uint16
        @overload
        def __init__(
            self,
            logical_block_number: _c_udf.uint32 | None = ...,
            partition_reference_number: _c_udf.uint16 | None = ...,
        ): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

    class udf_short_allocation_descriptor(__cs__.Structure):
        extent_length: _c_udf.uint32
        extent_position: _c_udf.uint32
        @overload
        def __init__(self, extent_length: _c_udf.uint32 | None = ..., extent_position: _c_udf.uint32 | None = ...): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

    class udf_long_allocation_descriptor(__cs__.Structure):
        extent_length: _c_udf.uint32
        extent_location: _c_udf.udf_lb_addr
        implementation_use: __cs__.CharArray
        @overload
        def __init__(
            self,
            extent_length: _c_udf.uint32 | None = ...,
            extent_location: _c_udf.udf_lb_addr | None = ...,
            implementation_use: __cs__.CharArray | None = ...,
        ): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

    class udf_file_set_descriptor(__cs__.Structure):
        descriptor_tag: _c_udf.udf_tag
        recording_date_and_time: _c_udf.udf_timestamp
        interchange_level: _c_udf.uint16
        maximum_interchange_level: _c_udf.uint16
        character_set_list: _c_udf.uint32
        maximum_character_set_list: _c_udf.uint32
        file_set_number: _c_udf.uint32
        file_set_descriptor_number: _c_udf.uint32
        logical_volume_identifier_character_set: _c_udf.udf_charspec
        logical_volume_identifier: __cs__.CharArray
        file_set_character_set: _c_udf.udf_charspec
        file_set_identifier: __cs__.CharArray
        copyright_file_identifier: __cs__.CharArray
        abstract_file_identifier: __cs__.CharArray
        root_directory_icb: _c_udf.udf_long_allocation_descriptor
        domain_identifier: _c_udf.udf_entity_id
        next_extent: _c_udf.udf_long_allocation_descriptor
        system_stream_directory_icb: _c_udf.udf_long_allocation_descriptor
        reserved: __cs__.CharArray
        @overload
        def __init__(
            self,
            descriptor_tag: _c_udf.udf_tag | None = ...,
            recording_date_and_time: _c_udf.udf_timestamp | None = ...,
            interchange_level: _c_udf.uint16 | None = ...,
            maximum_interchange_level: _c_udf.uint16 | None = ...,
            character_set_list: _c_udf.uint32 | None = ...,
            maximum_character_set_list: _c_udf.uint32 | None = ...,
            file_set_number: _c_udf.uint32 | None = ...,
            file_set_descriptor_number: _c_udf.uint32 | None = ...,
            logical_volume_identifier_character_set: _c_udf.udf_charspec | None = ...,
            logical_volume_identifier: __cs__.CharArray | None = ...,
            file_set_character_set: _c_udf.udf_charspec | None = ...,
            file_set_identifier: __cs__.CharArray | None = ...,
            copyright_file_identifier: __cs__.CharArray | None = ...,
            abstract_file_identifier: __cs__.CharArray | None = ...,
            root_directory_icb: _c_udf.udf_long_allocation_descriptor | None = ...,
            domain_identifier: _c_udf.udf_entity_id | None = ...,
            next_extent: _c_udf.udf_long_allocation_descriptor | None = ...,
            system_stream_directory_icb: _c_udf.udf_long_allocation_descriptor | None = ...,
            reserved: __cs__.CharArray | None = ...,
        ): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

    class udf_file_identifier_descriptor(__cs__.Structure):
        descriptor_tag: _c_udf.udf_tag
        file_version_number: _c_udf.uint16
        file_characteristics: _c_udf.uint8
        length_of_file_identifier: _c_udf.uint8
        icb: _c_udf.udf_long_allocation_descriptor
        length_of_implementation_use: _c_udf.uint16
        implementation_use: __cs__.CharArray
        file_identifier: __cs__.CharArray
        @overload
        def __init__(
            self,
            descriptor_tag: _c_udf.udf_tag | None = ...,
            file_version_number: _c_udf.uint16 | None = ...,
            file_characteristics: _c_udf.uint8 | None = ...,
            length_of_file_identifier: _c_udf.uint8 | None = ...,
            icb: _c_udf.udf_long_allocation_descriptor | None = ...,
            length_of_implementation_use: _c_udf.uint16 | None = ...,
            implementation_use: __cs__.CharArray | None = ...,
            file_identifier: __cs__.CharArray | None = ...,
        ): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

    class udf_icb_strategy_type(__cs__.Enum):
        UNDEF = ...
        STRATEGY_1 = ...
        STRATEGY_2 = ...
        STRATEGY_3 = ...
        STRATEGY_4 = ...

    class udf_icb_file_type(__cs__.Enum):
        UNDEF = ...
        USE = ...
        PIE = ...
        IE = ...
        DIRECTORY = ...
        REGULAR = ...
        BLOCK = ...
        CHAR = ...
        EA = ...
        FIFO = ...
        SOCKET = ...
        TE = ...
        SYMLINK = ...
        STREAMDIR = ...

    class udf_icb_tag_allocation_type(__cs__.Enum):
        short_descriptors = ...
        long_descriptors = ...
        extended_descriptors = ...
        embedded = ...

    class udf_icb_tag_flags(__cs__.Structure):
        allocation_type: _c_udf.uint16
        sort_directory: _c_udf.uint16
        non_relocatable: _c_udf.uint16
        archive: _c_udf.uint16
        S_ISUID: _c_udf.uint16
        S_ISGID: _c_udf.uint16
        C_ISVTX: _c_udf.uint16
        contiguous: _c_udf.uint16
        system: _c_udf.uint16
        transformed: _c_udf.uint16
        multi_versions: _c_udf.uint16
        stream: _c_udf.uint16
        reserved: _c_udf.uint16
        @overload
        def __init__(
            self,
            allocation_type: _c_udf.uint16 | None = ...,
            sort_directory: _c_udf.uint16 | None = ...,
            non_relocatable: _c_udf.uint16 | None = ...,
            archive: _c_udf.uint16 | None = ...,
            S_ISUID: _c_udf.uint16 | None = ...,
            S_ISGID: _c_udf.uint16 | None = ...,
            C_ISVTX: _c_udf.uint16 | None = ...,
            contiguous: _c_udf.uint16 | None = ...,
            system: _c_udf.uint16 | None = ...,
            transformed: _c_udf.uint16 | None = ...,
            multi_versions: _c_udf.uint16 | None = ...,
            stream: _c_udf.uint16 | None = ...,
            reserved: _c_udf.uint16 | None = ...,
        ): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

    class udf_icb_tag(__cs__.Structure):
        prior_recorded_number_of_direct_entries: _c_udf.uint32
        strategy_type: _c_udf.udf_icb_strategy_type
        strategy_parameter: __cs__.CharArray
        maximum_number_of_entries: _c_udf.uint16
        reserved: _c_udf.char
        file_type: _c_udf.udf_icb_file_type
        parent_icb_location: _c_udf.udf_lb_addr
        flags: _c_udf.udf_icb_tag_flags
        @overload
        def __init__(
            self,
            prior_recorded_number_of_direct_entries: _c_udf.uint32 | None = ...,
            strategy_type: _c_udf.udf_icb_strategy_type | None = ...,
            strategy_parameter: __cs__.CharArray | None = ...,
            maximum_number_of_entries: _c_udf.uint16 | None = ...,
            reserved: _c_udf.char | None = ...,
            file_type: _c_udf.udf_icb_file_type | None = ...,
            parent_icb_location: _c_udf.udf_lb_addr | None = ...,
            flags: _c_udf.udf_icb_tag_flags | None = ...,
        ): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

    class udf_file_entry(__cs__.Structure):
        icb_tag: _c_udf.udf_icb_tag
        uid: _c_udf.uint32
        gid: _c_udf.uint32
        permissions: _c_udf.uint32
        file_link_count: _c_udf.uint16
        record_format: _c_udf.uint8
        record_display_attributes: _c_udf.uint8
        record_length: _c_udf.uint32
        information_length: _c_udf.uint64
        logical_blocks_recorded: _c_udf.uint64
        access_time: _c_udf.udf_timestamp
        modification_time: _c_udf.udf_timestamp
        attribute_time: _c_udf.udf_timestamp
        checkpoint: _c_udf.uint32
        extended_attribute_icb: _c_udf.udf_long_allocation_descriptor
        implementation_identifier: _c_udf.udf_entity_id
        unique_id: _c_udf.uint64
        length_of_extended_attributes: _c_udf.uint32
        length_of_allocation_descriptors: _c_udf.uint32
        extended_attributes: __cs__.CharArray
        allocation_descriptors: __cs__.CharArray
        @overload
        def __init__(
            self,
            icb_tag: _c_udf.udf_icb_tag | None = ...,
            uid: _c_udf.uint32 | None = ...,
            gid: _c_udf.uint32 | None = ...,
            permissions: _c_udf.uint32 | None = ...,
            file_link_count: _c_udf.uint16 | None = ...,
            record_format: _c_udf.uint8 | None = ...,
            record_display_attributes: _c_udf.uint8 | None = ...,
            record_length: _c_udf.uint32 | None = ...,
            information_length: _c_udf.uint64 | None = ...,
            logical_blocks_recorded: _c_udf.uint64 | None = ...,
            access_time: _c_udf.udf_timestamp | None = ...,
            modification_time: _c_udf.udf_timestamp | None = ...,
            attribute_time: _c_udf.udf_timestamp | None = ...,
            checkpoint: _c_udf.uint32 | None = ...,
            extended_attribute_icb: _c_udf.udf_long_allocation_descriptor | None = ...,
            implementation_identifier: _c_udf.udf_entity_id | None = ...,
            unique_id: _c_udf.uint64 | None = ...,
            length_of_extended_attributes: _c_udf.uint32 | None = ...,
            length_of_allocation_descriptors: _c_udf.uint32 | None = ...,
            extended_attributes: __cs__.CharArray | None = ...,
            allocation_descriptors: __cs__.CharArray | None = ...,
        ): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

    class udf_component_type(__cs__.Enum):
        RESERVED = ...
        ROOT = ...
        PATH_ROOT = ...
        PARENT = ...
        CURDIR = ...
        IDENTIFIER = ...

    class udf_path_component(__cs__.Structure):
        component_type: _c_udf.uint8
        length_of_component_identifier: _c_udf.uint8
        component_file_version_number: _c_udf.uint16
        component_identifier: __cs__.CharArray
        @overload
        def __init__(
            self,
            component_type: _c_udf.uint8 | None = ...,
            length_of_component_identifier: _c_udf.uint8 | None = ...,
            component_file_version_number: _c_udf.uint16 | None = ...,
            component_identifier: __cs__.CharArray | None = ...,
        ): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

    class udf_extended_file_entry(__cs__.Structure):
        icb_tag: _c_udf.udf_icb_tag
        uid: _c_udf.uint32
        gid: _c_udf.uint32
        permissions: _c_udf.uint32
        file_link_count: _c_udf.uint16
        record_format: _c_udf.uint8
        record_display_attributes: _c_udf.uint8
        record_length: _c_udf.uint32
        information_length: _c_udf.uint64
        object_size: _c_udf.uint64
        logical_blocks_recorded: _c_udf.uint64
        access_time: _c_udf.udf_timestamp
        modification_time: _c_udf.udf_timestamp
        creation_time: _c_udf.udf_timestamp
        attribute_time: _c_udf.udf_timestamp
        checkpoint: _c_udf.uint32
        reserved: __cs__.CharArray
        extended_attribute_icb: _c_udf.udf_long_allocation_descriptor
        stream_directory_icb: _c_udf.udf_long_allocation_descriptor
        implementation_identifier: _c_udf.udf_entity_id
        unique_id: _c_udf.uint64
        length_of_extended_attributes: _c_udf.uint32
        length_of_allocation_descriptors: _c_udf.uint32
        extended_attributes: __cs__.CharArray
        allocation_descriptors: __cs__.CharArray
        @overload
        def __init__(
            self,
            icb_tag: _c_udf.udf_icb_tag | None = ...,
            uid: _c_udf.uint32 | None = ...,
            gid: _c_udf.uint32 | None = ...,
            permissions: _c_udf.uint32 | None = ...,
            file_link_count: _c_udf.uint16 | None = ...,
            record_format: _c_udf.uint8 | None = ...,
            record_display_attributes: _c_udf.uint8 | None = ...,
            record_length: _c_udf.uint32 | None = ...,
            information_length: _c_udf.uint64 | None = ...,
            object_size: _c_udf.uint64 | None = ...,
            logical_blocks_recorded: _c_udf.uint64 | None = ...,
            access_time: _c_udf.udf_timestamp | None = ...,
            modification_time: _c_udf.udf_timestamp | None = ...,
            creation_time: _c_udf.udf_timestamp | None = ...,
            attribute_time: _c_udf.udf_timestamp | None = ...,
            checkpoint: _c_udf.uint32 | None = ...,
            reserved: __cs__.CharArray | None = ...,
            extended_attribute_icb: _c_udf.udf_long_allocation_descriptor | None = ...,
            stream_directory_icb: _c_udf.udf_long_allocation_descriptor | None = ...,
            implementation_identifier: _c_udf.udf_entity_id | None = ...,
            unique_id: _c_udf.uint64 | None = ...,
            length_of_extended_attributes: _c_udf.uint32 | None = ...,
            length_of_allocation_descriptors: _c_udf.uint32 | None = ...,
            extended_attributes: __cs__.CharArray | None = ...,
            allocation_descriptors: __cs__.CharArray | None = ...,
        ): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

    class udf_virtual_partition_map(__cs__.Structure):
        partition_map_type: _c_udf.uint8
        partition_map_length: _c_udf.uint8
        reserved: __cs__.CharArray
        partition_type_identifier: __cs__.CharArray
        volume_sequence_number: _c_udf.uint16
        partition_number: _c_udf.uint16
        reserved2: __cs__.CharArray
        @overload
        def __init__(
            self,
            partition_map_type: _c_udf.uint8 | None = ...,
            partition_map_length: _c_udf.uint8 | None = ...,
            reserved: __cs__.CharArray | None = ...,
            partition_type_identifier: __cs__.CharArray | None = ...,
            volume_sequence_number: _c_udf.uint16 | None = ...,
            partition_number: _c_udf.uint16 | None = ...,
            reserved2: __cs__.CharArray | None = ...,
        ): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

    class udf_sparable_partition_map(__cs__.Structure):
        partition_map_type: _c_udf.uint8
        partition_map_length: _c_udf.uint8
        reserved: __cs__.CharArray
        partition_type_identifier: __cs__.CharArray
        volume_sequence_number: _c_udf.uint16
        partition_number: _c_udf.uint16
        packet_length: _c_udf.uint16
        number_of_sparing_tables: _c_udf.uint8
        reserved2: __cs__.CharArray
        sparing_table_size: _c_udf.uint32
        sparing_tables: __cs__.CharArray
        @overload
        def __init__(
            self,
            partition_map_type: _c_udf.uint8 | None = ...,
            partition_map_length: _c_udf.uint8 | None = ...,
            reserved: __cs__.CharArray | None = ...,
            partition_type_identifier: __cs__.CharArray | None = ...,
            volume_sequence_number: _c_udf.uint16 | None = ...,
            partition_number: _c_udf.uint16 | None = ...,
            packet_length: _c_udf.uint16 | None = ...,
            number_of_sparing_tables: _c_udf.uint8 | None = ...,
            reserved2: __cs__.CharArray | None = ...,
            sparing_table_size: _c_udf.uint32 | None = ...,
            sparing_tables: __cs__.CharArray | None = ...,
        ): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

    class udf_sparing_table(__cs__.Structure):
        descriptor_tag: _c_udf.udf_tag
        sparing_table_identifier: _c_udf.udf_entity_id
        reallocation_table_length: _c_udf.uint16
        reserved: __cs__.CharArray
        map_entry_buf: __cs__.CharArray
        @overload
        def __init__(
            self,
            descriptor_tag: _c_udf.udf_tag | None = ...,
            sparing_table_identifier: _c_udf.udf_entity_id | None = ...,
            reallocation_table_length: _c_udf.uint16 | None = ...,
            reserved: __cs__.CharArray | None = ...,
            map_entry_buf: __cs__.CharArray | None = ...,
        ): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

    class udf_map_entry(__cs__.Structure):
        original_location: _c_udf.uint32
        mapped_location: _c_udf.uint32
        @overload
        def __init__(
            self, original_location: _c_udf.uint32 | None = ..., mapped_location: _c_udf.uint32 | None = ...
        ): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

# Technically `c_udf` is an instance of `_c_udf`, but then we can't use it in type hints
c_udf: TypeAlias = _c_udf
